package com.hassine.enumerations;

public enum Nationality {
    Afghan("Afghan"),
    Albanian("Albanian"),
    Algerian("Algerian"),
    American("American"),
    Andorran("Andorran"),
    Antiguan("Antiguan"),
    Argentinian("Argentinian"),
    Armenian("Armenian"),
    Australian("Australian"),
    Austrian("Austrian"),
    Azerbaijani("Azerbaijani"),
    Bahamian("Bahamian"),
    Bahraini("Bahraini"),
    Bangladeshi("Bangladeshi"),
    Barbadian("Barbadian"),
    Batswana("Batswana"),
    Belarusian("Belarusian"),
    Belgian("Belgian"),
    Belizean("Belizean"),
    Beninese("Beninese"),
    Bhutanese("Bhutanese"),
    Bissau_Guinean("Bissau_Guinean"),
    Bolivian("Bolivian"),
    Bosniak("Bosniak"),
    Brazilian("Brazilian"),
    British("British"),
    Bruneian("Bruneian"),
    Bulgarian("Bulgarian"),
    Burkinabé("Burkinabé"),
    Burmese("Burmese"),
    Burundian("Burundian"),
    Cambodian("Cambodian"),
    Cameroonian("Cameroonian"),
    Canadian("Canadian"),
    Cape_Verdean("Cape Verdean"),
    Central_African("Central African"),
    Chadian("Chadian"),
    Chilean("Chilean"),
    Chinese("Chinese"),
    Colombian("Colombian"),
    Comorian("Comorian"),
    Congolese_Democratic_Republic_of_the_Congo("Congolese:RDC"),
    Congolese_Republic_of_the_Congo("Congolese:Congo Brazzaville"),
    Costa_Rican("Costa Rican"),
    Croatian("Croatian"),
    Cuban("Cuban"),
    Cypriot("Cypriot"),
    Czech("Czech"),
    Danish("Danish"),
    Djiboutien("Djiboutien"),
    Dominican_Dominica("Dominican:Dominica"),
    Dominican_Dominican_Republic("Dominican:Dominican Republic"),
    Dutch("Dutch"),
    East_Timorese("East Timorese"),
    Ecuadorian("Ecuadorian"),
    Egyptian("Egyptian"),
    Salvadorian("Salvadorian"),
    Emirati("Emirati"),
    Equatoguinean("Equatoguinean"),
    Eritrean("Eritrean"),
    Estonian("Estonian"),
    Ethiopian("Ethiopian"),
    Fijian("Fijian"),
    Finnish("Finnish"),
    French("French"),
    Gabonese("Gabonese"),
    Gambian("Gambian"),
    Georgian("Georgian"),
    German("German"),
    Ghanaian("Ghanaian"),
    Greek("Greek"),
    Grenadian("Grenadian"),
    Guatemalan("Guatemalan"),
    Guinean("Guinean"),
    Guyanese("Guyanese"),
    Haitian("Haitian"),
    Honduran("Honduran"),
    Hungarian("Hungarian"),
    Icelandic("Icelandic"),
    Indian("Indian"),
    Indonesian("Indonesian"),
    Iranian("Iranian"),
    Iraqi("Iraqi"),
    Irish("Irish"),
    Israeli("Israeli"),
    Italian("Italian"),
    Ivoirien("Ivoirien"),
    Jamaican("Jamaican"),
    Japanese("Japanese"),
    Jordanian("Jordanian"),
    Kazakh("Kazakh"),
    Kenyan("Kenyan"),
    Kiribati("Kiribati"),
    Kittitian("Kittitian"),
    Kosovar("Kosovar"),
    Kuwaiti("Kuwaiti"),
    Kyrgyzstani("Kyrgyzstani"),
    Lao("Lao"),
    Latvian("Latvian"),
    Lebanese("Lebanese"),
    Liberian("Liberian"),
    Libyan("Libyan"),
    Liechtensteiner("Liechtensteiner"),
    Lithuanian("Lithuanian"),
    Luxembourgish("Luxembourgish"),
    Macedonian("Macedonian"),
    Malagasy("Malagasy"),
    Malawian("Malawian"),
    Malaysian("Malaysian"),
    Maldivian("Maldivian"),
    Malian("Malian"),
    Maltese("Maltese"),
    Marshallese("Marshallese"),
    Mauritanian("Mauritanian"),
    Mauritian("Mauritian"),
    Mexican("Mexican"),
    Micronesian("Micronesian"),
    Moldovan("Moldovan"),
    Monégasque("Monégasque"),
    Mongolian("Mongolian"),
    Montenegrin("Montenegrin"),
    Moroccan("Moroccan"),
    Mosotho("Mosotho"),
    Mozambican("Mozambican"),
    Namibian("Namibian"),
    Nauruan("Nauruan"),
    Nepalese("Nepalese"),
    New_Zealand("New Zealand"),
    Ni_Vanuatu("Ni-Vanuatu"),
    Nicaraguan("Nicaraguan"),
    Nigerian("Nigerian"),
    Nigerien("Nigerien"),
    North_Korean("North Korean"),
    Norwegian("Norwegian"),
    Omani("Omani"),
    Pakistani("Pakistani"),
    Palauan("Palauan"),
    Panamanian("Panamanian"),
    Papua_New_Guinean("Papua New Guinean"),
    Paraguayan("Paraguayan"),
    Peruvian("Peruvian"),
    Philippine("Philippine"),
    Polish("Polish"),
    Portuguese("Portuguese"),
    Qatari("Qatari"),
    Romanian("Romanian"),
    Russian("Russian"),
    Rwandan("Rwandan"),
    Saint_Lucian("Saint Lucian"),
    Saint_Vincentian("Saint_Vincentian"),
    Sammarinese("Sammarinese"),
    Samoan("Samoan"),
    São_Toméan("São_Toméan"),
    Saudi("Saudi"),
    Senegalese("Senegalese"),
    Seychellois("Seychellois"),
    Serbian("Serbian"),
    Sierra_Leonean("Sierra_Leonean"),
    Singaporean("Singaporean"),
    Slovak("Slovak"),
    Slovenian("Slovenian"),
    Solomon_Islander("Solomon Islander"),
    Somalian("Somalian"),
    South_African("South African"),
    South_Korean("South Korean"),
    South_Sudanese("South Sudanese"),
    Spanish("Spanish"),
    Sri_Lankan("Sri Lankan"),
    Sudanese("Sudanese"),
    Surinamer("Surinamer"),
    Swazi("Swazi"),
    Swedish("Swedish"),
    Swiss("Swiss"),
    Syrian("Syrian"),
    Taiwanese("Taiwanese"),
    Tajikistani("Tajikistani"),
    Tanzanian("Tanzanian"),
    Thai("Thai"),
    Tobagonian("Tobagonian"),
    Togolese("Togolese"),
    Tongan("Tongan"),
    Tunisian("Tunisian"),
    Turkish("Turkish"),
    Turkmen("Turkmen"),
    Tuvaluan("Tuvaluan"),
    Ugandan("Ugandan"),
    Ukrainian("Ukrainian"),
    Uruguayan("Uruguayan"),
    Uzbek("Uzbek"),
    Venezuelan("Venezuelan"),
    Vietnamese("Vietnamese"),
    Yemeni("Yemeni"),
    Zambian("Zambian"),
    Zimbabwean("Zimbabwean");

    private final String nationalityLabel;

    Nationality(String nationalityLabel) {
        this.nationalityLabel = nationalityLabel;
    }

    public String getNationalityLabel() {
        return nationalityLabel;
    }

}
