package com.hassine.enumerations;

public enum Nationality {
    Afghan("Afghan"),
    Albanian("Albanian"),
    Algerian("Algerian"),
    American("American "),
    Andorran("Andorran"),
    Antiguan("Antiguan"),
    Argentinian("Argentinian"),
    Armenian("Armenian"),
    Australian("Australian"),
    Austrian("Austrian"),
    Azerbaijani("Azerbaijani"),
    Bahamian("Bahamian"),
    Bahraini("Bahraini"),
    Bangladeshi("Bangladeshi"),
    Barbadian("Barbadian"),
    Batswana("Batswana"),
    Belarusian("Belarusian"),
    Belgian("Belgian"),
    Belizean("Belizean"),
    Beninese("Beninese"),
    Bhutanese("Bhutanese"),
    Bolivian("Bolivian"),
    Bosniak("Bosniak"),
    Brazilian("Brazilian"),
    British("British"),
    Bruneian("Bruneian"),
    Bulgarian("Bulgarian"),
    Burkinabé("Burkinabé"),
    Burundian("Burundian"),
    Cambodian("Cambodian"),
    Cameroonian("Cameroonian"),
    Canadian("Canadian"),
    Chilean("Chilean"),
    Chinese("Chinese"),
    Colombian("Colombian"),
    Costa_Rican("Costa Rican"),
    Croatian("Croatian"),
    Cuban("Cuban"),
    Czech("Czech"),
    Danish("Danish"),
    Dominican("Dominican"),
    Dutch("Dutch"),
    Ecuadorian("Ecuadorian"),
    Egyptian("Egyptian"),
    Salvadorian("Salvadorian"),
    Emirati("Emirati"),
    Estonian("Estonian"),
    Ethiopian("Ethiopian"),
    Fijian("Fijian"),
    Finnish("Finnish"),
    French("French"),
    German("German"),
    Ghanaian("Ghanaian"),
    Greek("Greek"),
    Guatemalan("Guatemalan"),
    Haitian("Haitian"),
    Honduran("Honduran"),
    Hungarian("Hungarian"),
    Icelandic("Icelandic"),
    Indian("Indian"),
    Indonesian("Indonesian"),
    Iranian("Iranian"),
    Iraqi("Iraqi"),
    Irish("Irish"),
    Israeli("Israeli"),
    Italian("Italian"),
    Jamaican("Jamaican"),
    Japanese("Japanese"),
    Jordanian("Jordanian"),
    Kenyan("Kenyan"),
    Korean("Korean"),
    Kuwaiti("Kuwaiti"),
    Lao("Lao"),
    Latvian("Latvian"),
    Lebanese("Lebanese"),
    Libyan("Libyan"),
    Lithuanian("Lithuanian"),
    Malaysian("Malaysian"),
    Malian("Malian"),
    Maltese("Maltese"),
    Mexican("Mexican"),
    Mongolian("Mongolian"),
    Moroccan("Moroccan"),
    Mozambican("Mozambican"),
    Namibian("Namibian"),
    Nepalese("Nepalese"),
    New_Zealand("New Zealand"),
    Nicaraguan("Nicaraguan"),
    Nigerian("Nigerian"),
    Norwegian("Norwegian"),
    Pakistani("Pakistani"),
    Panamanian("Panamanian"),
    Paraguayan("Paraguayan"),
    Peruvian("Peruvian"),
    Philippine("Philippine"),
    Polish("Polish"),
    Portuguese("Portuguese"),
    Romanian("Romanian"),
    Russian("Russian"),
    Saudi("Saudi"),
    Senegalese("Senegalese"),
    Serbian("Serbian"),
    Singaporean("Singaporean"),
    Slovak("Slovak"),
    South_African("South African"),
    Spanish("Spanish"),
    Sri_Lankan("Sri Lankan"),
    Sudanese("Sudanese"),
    Swedish("Swedish"),
    Swiss("Swiss"),
    Syrian("Syrian"),
    Taiwanese("Taiwanese"),
    Tajikistani("Tajikistani"),
    Thai("Thai"),
    Tongan("Tongan"),
    Tunisian("Tunisian"),
    Turkish("Turkish"),
    Ukrainian("Ukrainian"),
    Uruguayan("Uruguayan"),
    Venezuelan("Venezuelan"),
    Vietnamese("Vietnamese"),
    Zambian("Zambian"),
    Zimbabwean("Zimbabwean");

    private final String nationalityLabel;

    Nationality(final String label) {
        nationalityLabel = label;
    }

    @Override
    public String toSring() {
        return nationalityLabel;
    }

}
